# Generated by Django 5.2.5 on 2025-08-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phase", models.CharField(max_length=50)),
                ("sequence", models.IntegerField()),
                ("topic", models.CharField(max_length=200)),
                ("description", models.TextField()),
            ],
        ),
    ]
